# 최상위 경로의 values.yaml
# 각각의 차트에 전달할 글로벌 values를 정의

index-app:
  replicas: 2
  image:
    tag: "1.0"
  service:
    port: 80
  containerPort: 80
  enabled: true

market-app: 
  replicas: 2
  image:
    tag: "1.0"
  service:
    port: 8000
  containerPort: 8000
  enabled: true

post-app:
  replicas: 2
  image:
    tag: "1.0"
  service:
    port: 8000
  containerPort: 8000
  enabled: true